---
- name: add domain to hosts
  lineinfile: 
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1    {{ ansible_hostname }} {{ domain }}"
    state: present
  
- name: setup debconf postfix domain
  debconf:
    name: postfix
    question: postfix/mailname
    value: '{{ domain }}'
    vtype: string

- name: setup debconf postfix type
  debconf:
    name: postfix
    question: postfix/main_mailer_type              
    value: 'Internet Site'
    vtype: string

- name: Apt Update cache
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - letsencrypt
    - curl
    - ca-certificates
    - postfix

- name: Download Script repo
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh dest=/tmp/script.deb.sh mode=755

- name: Execute the script
  shell: /tmp/script.deb.sh

- name: install gitlab
  apt: 
    name: gitlab-ee

- name: configure url
  lineinfile: 
    path: /etc/gitlab/gitlab.rb
    regexp: '^external_url '
    line: 'external_url "http://{{ domain }}"'
    state: present

- name: configure url
  lineinfile: 
    path: /etc/gitlab/gitlab.rb
    regexp: "^letsencrypt['enable'] ="
    line: "letsencrypt['enable'] = true"
    state: present
  when: ( letsencrypt == true )

- name: configure url
  lineinfile: 
    path: /etc/gitlab/gitlab.rb
    regexp: "^letsencrypt['contact_emails'] ="
    line: "letsencrypt['contact_emails'] = ['{{ email }}']"
    state: present
  when: ( letsencrypt == true )

- name: Running gitlab
  shell: "gitlab-ctl reconfigure"
    async: 10000
    poll: 0
